# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # USB passthrough for Security Key by Yubico
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'fido2', '--vendorid', '0x1050', '--productid', '0x0120']
  end

  config.vm.provision "shell", inline: <<-SHELL
    # See https://launchpad.net/~yubico
    apt-add-repository ppa:yubico/stable
    apt-get update
    # libfido2-udev provides /lib/udev/rules.d/70-u2f.rules
    apt-get install -y libfido2-dev libfido2-udev fido2-tools make
    # add vagrant user to plugdev group -- you may need to re-insert your security key
    usermod -a -G plugdev vagrant
  SHELL
end
